name: Android CI

on:
    push:
        branches: ["main", "feature/processing"]
    pull_request:
        branches: ["main"]

jobs:
    clear:
        runs-on: windows-latest
        name: Delete old workflow runs
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Delete workflow runs
              uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
              with:
                  repository: Florian-Thauvin/PokeScan
                  workflow: ".github/workflows/android.yml"
                  older-than-seconds: 86400
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    android:
        runs-on: macos-latest
        name: Test on API ${{ matrix.api-level }}
        strategy:
            matrix:
                api-level: [26, 29]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "temurin"
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew clean build -x test
            - name: Gradle cache
              uses: gradle/gradle-build-action@v2
            - name: AVD cache
              uses: actions/cache@v3
              id: avd-cache
              with:
                  path: |
                      ~/.android/avd/*
                      ~/.android/adb*
                  key: avd-${{ matrix.api-level }}

            - name: Create AVD and generate snapshot for caching
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: false
                  script: echo "Generated AVD snapshot for caching."

            - name: Run unit tests
              run: ./gradlew test
            - name: Run connected tests
              continue-on-error: true
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  script: ./gradlew connectedCheck

            - name: Scan code
              run: ./gradlew build --scan

            - name: Setup sonarqube
              uses: warchant/setup-sonar-scanner@v3
            - name: Run sonarqube
              run: sonar-scanner
                  -Dsonar.host.url=${{ secrets.SONAR_URL }}
                  -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                  -Dsonar.organization="Florian Thauvin"
                  -Dsonar.projectKey=PokeScan
